version: '3.8'

services:
  github-analysis:
    build: .
    image: github-analysis
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./visualizations:/app/visualizations
    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1