repos:
  - owner: tensorflow
    name: tensorflow
    positioning: performance
  - owner: scikit-learn
    name: scikit-learn
    positioning: performance
  - owner: numpy
    name: numpy
    positioning: performance
  - owner: pola-rs
    name: polars
    positioning: performance
  - owner: pandas-dev
    name: pandas
    positioning: simplicity
  - owner: matplotlib
    name: matplotlib
    positioning: simplicity
  - owner: mwaskom
    name: seaborn
    positioning: simplicity
  - owner: plotly
    name: plotly.py
    positioning: simplicity